---
- block:
  - name: upgrade kernel
    apt:
      state: latest
      name: linux-generic-lts-xenial
      autoremove: yes
      install_recommends: yes
      cache_valid_time: 3600
    notify:
      - reboot_linux
      - wait_reboot_linux
    when: ubuntu_kernel_upgrade == true

  - name: upgrade apt_packages
    apt:
      upgrade: dist
      autoremove: yes
      cache_valid_time: 3600
    notify:
      - reboot_linux
      - wait_reboot_linux
    when: ubuntu_packages_upgrade == true

  - meta: flush_handlers
  become: true