---
- block:
  - name: import nodejs public GPG Key
    apt_key:
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
      id: "68576280"
      state: present

  - name: add nodejs source repo
    apt_repository:
      repo: 'deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main'
      update_cache: yes

  - name: install nodejs
    apt:
      name: nodejs
      cache_valid_time: 3600

  - name: read npm registry
    shell: "npm get registry -g"
    register: npm_current_registry
    changed_when: false

  - name: set npm registry
    shell: "npm set registry -g '{{ npm_registry_url }}'"
    changed_when: npm_current_registry.stdout != npm_registry_url

  - name: get current node version
    command: node -v
    register: current_node_version
    changed_when: false

  - name: install node package manager
    npm:
      name: n
      state: latest
      global: yes
    when: current_node_version.stdout != "v{{ node_full_version }}"

  - name: install node version {{ node_full_version }}
    command: n {{ node_full_version }}
    when: current_node_version.stdout != "v{{ node_full_version }}"

  - name: install npm version {{ npm_full_version }}
    npm:
      name: npm
      version: '{{ npm_full_version }}'
      global: yes

  become: true